name = input("Enter your name:")
age = int(input("Enter your age:"))
marks = float(input("Enter your Cgpa:"))
print("Hello ",name)
print("You are",age,"years old.")
print(type(name))
print(type(age))
print(type(marks))